105 UI
bbc/digital-paper-edit-firebase pull request #268
Opened 2021-05-27 09:02 UTC by allishultes

**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      

See [#105 in Storybook](https://github.com/bbc/digital-paper-edit-storybook/issues/105) 

**Describe what the PR does**    

- [x] Adds warning if user tries to close DPE tab when media is uploading
- [x] Adds prompt if user tries to navigate away from DPE while media is uploading

**State whether the PR is ready for review or whether it needs extra work**    

WIP

**Additional context**    

Please review [with the related Storybook PR](https://github.com/bbc/digital-paper-edit-storybook/pull/106) to see all of the fixes for the relevant issue. 

<!-- 
## User Story / Context
|As a ...|I want ...|So that ...|
|-|-|-|
|<Who>|<What>|<Why>|

## Acceptance Criteria
- <Criteria to satisfy the PR Issue>

2021-05-27 09:18 UTC, allishultes commented on src/Components/Workspace/index.js
> +        event.returnValue = 'Your file has not finished uploading';
This only results in a custom message in Safari; there aren't ways to add custom messages for Firefox and Chome.

2021-06-09 10:00 UTC, aniablaziak approved these changes
Thanks Alli, this worked for me in Chrome, Firefox and Safari. 

Not related to this PR: I noticed that Safari is not letting me upload some file formats (.mp3, .mp4) 🤔

2021-06-09 12:32 UTC, tamsingreen requested changes
Code looks good - needs changes to only show the prompt on navigating away from DPE or closing the tab as upload continues when staying within the app :)

2021-06-10 08:18 UTC, allishultes commented
> Code looks good - needs changes to only show the prompt on navigating away from DPE or closing the tab as upload continues when staying within the app :)

I'm actually not able to replicate this on all files, Tamsin! I've navigated within the app when uploading two test files yesterday, and neither have finished uploading or started transcribing ...

<img width="1067" alt="Screenshot 2021-06-10 at 09 15 17" src="https://user-images.githubusercontent.com/22618458/121489860-66caa500-c9cc-11eb-843e-a8756544e848.png">

<img width="580" alt="Screenshot 2021-06-10 at 09 14 13" src="https://user-images.githubusercontent.com/22618458/121490099-9ed1e800-c9cc-11eb-9012-d5a58f8e8ea7.png">

<img width="583" alt="Screenshot 2021-06-10 at 09 13 38" src="https://user-images.githubusercontent.com/22618458/121490267-c3c65b00-c9cc-11eb-83e0-c05ee9e0ed96.png">

On a separate note, ideally these should probably have `status:fail` since they will never finish...

2021-06-17 10:28 UTC, tamsingreen approved these changes
No prompt when I navigate elsewhere in the app; prompt when I try to close the tab 💫

2021-06-17 11:45 UTC, merged