Implement Analytics
bbc/digital-paper-edit-firebase pull request #285
Opened 2021-06-21 13:54 UTC by sarahrainbow

Fixes #219  

This PR is to

- implement the missing analytics based on #216
- rename the existing analytics to make them easier to understand

See this page on [confluence](https://confluence.dev.bbc.co.uk/display/newslabs/Analytics+overview) to see what analytics should now be in place.

## Acceptance Criteria
- Analytics are implemented and appropriately named

To check the analytics, you can do so from within the network tab:
![Screenshot 2021-05-25 at 11 52 42](https://user-images.githubusercontent.com/26869008/119486236-f0813e00-bd4f-11eb-94ff-fb48838098ff.png)

2021-06-22 08:58 UTC, tamsingreen requested changes
Looks good - couple of tweaks to make before merging bar any further feedback from the meeting :)

2021-06-22 08:58 UTC, tamsingreen commented on src/Components/PaperEditor/ProgrammeScriptContainer/ExportDropdown/dist/programme-script-json-to-docx.dev.js
> +'use strict';
I think this transpiled version might have been included by mistake

2021-06-22 08:58 UTC, tamsingreen commented on src/App.js
>      const authListener = props.firebase.auth.onAuthStateChanged((user) =>
Can just remove the user param here to fix the lint error

2021-06-22 08:58 UTC, tamsingreen commented on src/Components/PaperEditor/ProgrammeScriptContainer/ExportDropdown/index.js
> +const ExportDropdown = ({ title, elements, transcripts, projectTitle, storage, trackEvent, handleGetMediaUrl }) => {
👌🏻

2021-06-22 08:58 UTC, tamsingreen commented on src/HelpOverlayTrigger.js
> +        <a
Alli's updated this code recently with the new user manual so could you pull in her changes from master?

2021-06-22 14:18 UTC, tamsingreen commented on src/App.js
>      const authListener = props.firebase.auth.onAuthStateChanged((user) =>
This is NOT the right answer, ignore me @sarahrainbow

2021-07-01 15:58 UTC, allishultes approved these changes
Looks reallyy good, pal! Couple itty bitty comments. I haven't been super thorough in scrutinising all of the network calls locally but lmk if that would be helpful!

2021-07-01 15:58 UTC, allishultes commented on src/Components/PaperEditor/ProgrammeScriptContainer/index.js
> +      props.trackEvent({ category: 'programme script - programme script panel', action: 'insert selection', name: insertedWords });
Very detailed tracking 👍

2021-07-01 15:58 UTC, allishultes commented on src/Components/Workspace/PaperEdits/index.js
> +  trackEvent: PropTypes.any
Should this be 

```suggestion
  trackEvent: PropTypes.func
```
?

2021-07-02 09:13 UTC, sarahrainbow commented on src/Components/Workspace/index.js
> +  const convertMediaButton = () => {
nice suggestion – will rename 👍

2021-07-02 09:14 UTC, sarahrainbow commented on src/Components/Workspace/PaperEdits/index.js
> +  trackEvent: PropTypes.any
good spot!

2021-07-05 09:02 UTC, merged