279: Password reset
bbc/digital-paper-edit-firebase pull request #286
Opened 2021-06-21 15:56 UTC by tamsingreen

**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      
#279 

**Describe what the PR does**    
- Implements the password reset flow [here](https://zpl.io/a8QLXG4) with a new /reset route
- Change the sign-in to match the design
- Fixes some old linting errors :)

**State whether the PR is ready for review or whether it needs extra work**    
RFR

**Additional context**    
I've not implemented the designs exactly as designed as the DPE header is a separate component that is visible after sign in and removing that would need a bit of refactoring, so I've just implemented the reset

**Acceptance Criteria**
- When the sign-in field is empty, on clicking Password reset it leads to that screen with an empty email field
- When the sign-in field is populated, on clicking Password reset it leads to that screen with the email field populated with that email
- When the email is invalid, or not registered with DPE an error message is shown (n.b. some validation errors are caught by the browser and look different from the design. The app handled errors use the closest design I could find in Bootstrap).
- After resetting a password, the success message is shown and the link to resend again takes you back to the reset form with the email field populated
- Resetting the password triggers an email to be sent to that account and the link to reset works

2021-06-22 10:52 UTC, allishultes approved these changes
Nice work! Just a few very small comments :)

2021-06-22 12:34 UTC, sarahrainbow commented
this AC didn't work for me `When the sign-in field is populated, on clicking Password reset it leads to that screen with the email field populated with that email`
Still get an empty email address field.

2021-06-22 12:39 UTC, tamsingreen commented on src/Components/PasswordReset/index.js
> +  <Container style={ { marginBottom: '5em', marginTop: '1em', border: '1px solid #6b6b6b',
Lol, I just noticed that ADR when looking at the open PRs, I had forgotten about it otherwise :(
Thank you - I'll re-work it

2021-06-22 12:40 UTC, tamsingreen commented on src/Components/PasswordReset/index.js
> +// HOC with router and firebase
Higher-Order Component - it's a component that wraps around another component to extend it's functionality but I'm not sure I understand them any more deeply than that 🥴

2021-06-22 12:52 UTC, sarahrainbow commented on src/Components/PasswordReset/index.js
> +// HOC with router and firebase
not just you!

2021-06-22 13:03 UTC, sarahrainbow commented
once signed in, the `sign in` element still displays, when it should be the `signed in as: ` and `sign out` button elements
<img width="947" alt="Screenshot 2021-06-22 at 13 58 15" src="https://user-images.githubusercontent.com/26869008/122929263-a6957300-d362-11eb-8645-dfa8552ca228.png">

2021-06-22 13:17 UTC, sarahrainbow requested changes
looks great other than the sign out button vanishing (as mentioned in previous comment)

2021-06-30 11:27 UTC, tamsingreen commented
Sign-in button has been re-instated as per Sarah's request - going to merge

2021-06-30 11:28 UTC, merged